export const categories = [
  {
    id: 0,
    name: "Электроника",
    iconSrc: "/catalog/electronics.png",
    subcategories: [
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
      {
        name: "Телефоны",
        items: [
          "Смартфоны",
          "Акссесуары",
          "Смарт-часы",
          "Ремешки",
          "Чехлы",
          "Защитные стекла",
        ],
      },
    ],
  },
  { id: 1, name: "Одежда", iconSrc: "/catalog/clothes.png" },
  { id: 2, name: "Обувь", iconSrc: "/catalog/shoes.png" },
  { id: 3, name: "Сад", iconSrc: "/catalog/plants.png" },
  { id: 4, name: "Детям", iconSrc: "/catalog/children.png" },
  { id: 5, name: "Быт", iconSrc: "/catalog/househould.png" },
  { id: 6, name: "Спорт", iconSrc: "/catalog/sports.png" },
  { id: 7, name: "Аптека", iconSrc: "/catalog/pharmacy.png" },
  { id: 8, name: "Ремонт", iconSrc: "/catalog/repair.png" },
  { id: 9, name: "Авто", iconSrc: "/catalog/cars.png" },
  { id: 10, name: "Мебель", iconSrc: "/catalog/furniture.png" },
];
